### ISSUE TITLE
Find a way to accommodate inexact match for attribute definition

### ISSUE THREAD

**Issue by katemorkeski** [WHOIGit/nes-lter-npp-transect#1]
http://vocab.nerc.ac.uk/collection/P01/current/INPPIIP4/ is close but not exact match for integrated_npp definition (difference in filter size). Is there a way to accommodate?

**Comment by sbeaulieu** [comment]
still no perfect match in http://vocab.nerc.ac.uk/collection/P01/current/
consider adjusting attribute definition to "Vertically-integrated net primary productivity measured as uptake rate of carbon per unit area of the water body [particulate >0.7um phase] per day"

**Comment by katemorkeski** [comment]
This change was not made for knb-lter-nes.16.3. Consider for next version.

**Comment by katemorkeski** [comment]
added phase designation in knb-lter-nes.16.4
