### ISSUE TITLE
next version: add provenance for extinction_coefficients.csv

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-npp-transect#2]
https://github.com/difontaine/EDI_npp_package/blob/4fb5d067bcceaf08ebe6fa82d191e96092fd90d9/npp_integrated_calcs.R#L235  extinction_coefficients.csv
link back to Pierre's output files https://github.com/pmarrec/nes-lter-kd-calculation/tree/main/output_files

**Comment by katemorkeski** [comment]
Decide whether to include as other entity or describe in methods.

**Comment by katemorkeski** [comment]
added link to commit in methods
