### ISSUE TITLE
next version: consider adjusting filter size category

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-npp-transect#7]
consider "water was pre-filtered through 200 um mesh" (e.g., see categories in https://github.com/WHOIGit/nes-lter-chl-transect/blob/master/catvars_nes-lter-chl-transect.txt). This may only apply to present category >0.

**Comment by katemorkeski** [comment]
I think this would apply only to incubation samples (i.e. where incub_type != ambient_temp).

**Comment by katemorkeski** [comment]
applied to all >0 samples
